// Copyright 2012 The d2d Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package d2d

type D2D1_FACTORY_TYPE uint32

const (
	D2D1_FACTORY_TYPE_SINGLE_THREADED D2D1_FACTORY_TYPE = 0
	D2D1_FACTORY_TYPE_MULTI_THREADED  D2D1_FACTORY_TYPE = 1
)

type D2D1_DEBUG_LEVEL uint32

const (
	D2D1_DEBUG_LEVEL_NONE        D2D1_DEBUG_LEVEL = 0
	D2D1_DEBUG_LEVEL_ERROR       D2D1_DEBUG_LEVEL = 1
	D2D1_DEBUG_LEVEL_WARNING     D2D1_DEBUG_LEVEL = 2
	D2D1_DEBUG_LEVEL_INFORMATION D2D1_DEBUG_LEVEL = 3
)

type D2D1_FILL_MODE uint32
const (
	D2D1_FILL_MODE_ALTERNATE D2D1_FILL_MODE = 0
	D2D1_FILL_MODE_WINDING D2D1_FILL_MODE = 1
)

type D2D1_CAP_STYLE uint32
const (
	D2D1_CAP_STYLE_FLAT D2D1_CAP_STYLE = 0
	D2D1_CAP_STYLE_SQUARE D2D1_CAP_STYLE = 1
	D2D1_CAP_STYLE_ROUND D2D1_CAP_STYLE = 2
	D2D1_CAP_STYLE_TRIANGLE D2D1_CAP_STYLE = 3
)

type D2D1_LINE_JOIN uint32
const (
	D2D1_LINE_JOIN_MITER D2D1_LINE_JOIN = 0
	D2D1_LINE_JOIN_BEVEL D2D1_LINE_JOIN = 1
	D2D1_LINE_JOIN_ROUND D2D1_LINE_JOIN = 2
	D2D1_LINE_JOIN_MITER_OR_BEVEL D2D1_LINE_JOIN = 3
)

type D2D1_DASH_STYLE uint32
const (
	D2D1_DASH_STYLE_SOLID D2D1_DASH_STYLE = 0
	D2D1_DASH_STYLE_DASH D2D1_DASH_STYLE = 1
	D2D1_DASH_STYLE_DOT D2D1_DASH_STYLE = 2
	D2D1_DASH_STYLE_DASH_DOT D2D1_DASH_STYLE = 3
	D2D1_DASH_STYLE_DASH_DOT_DOT D2D1_DASH_STYLE = 4
	D2D1_DASH_STYLE_CUSTOM D2D1_DASH_STYLE = 5
)
